
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format, fromUnixTime } from 'date-fns';
import { SeaTimeReportData } from '@/app/actions';

export function generateSeaTimeTestimonial(data: SeaTimeReportData) {
  const doc = new jsPDF();
  const { userProfile, serviceRecords, vesselDetails, totalDays, totalSeaDays, totalStandbyDays } = data;
  const fullName = `${userProfile.firstName || ''} ${userProfile.lastName || ''}`.trim() || userProfile.username;

  // Header
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('Sea Time Testimonial', 105, 20, { align: 'center' });

  // Crew Member Details
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Crew Member Details', 14, 35);
  autoTable(doc, {
    startY: 40,
    body: [
      ['Name:', fullName],
      ['Date of Birth:', ''], // Placeholder
      ['Nationality:', ''], // Placeholder
    ],
    theme: 'plain',
    styles: { fontSize: 11 },
  });

  // Vessel Details
  const currentY = (doc as any).lastAutoTable.finalY + 10;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Vessel Details', 14, currentY);
  autoTable(doc, {
    startY: currentY + 5,
    body: [
        ['Vessel Name:', vesselDetails?.name || 'Multiple Vessels'],
        ['Vessel Type:', vesselDetails?.type || 'N/A'],
        ['Official Number:', vesselDetails?.officialNumber || 'N/A'],
    ],
    theme: 'plain',
    styles: { fontSize: 11 },
  });

  // Sea Service Table
  const serviceTableY = (doc as any).lastAutoTable.finalY + 15;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Record of Sea Service', 14, serviceTableY);

  const tableBody = serviceRecords.map(record => [
    record.vesselName,
    record.position,
    format(fromUnixTime(record.startDate.seconds), 'dd-MMM-yyyy'),
    record.endDate ? format(fromUnixTime(record.endDate.seconds), 'dd-MMM-yyyy') : 'Current',
    record.totalDays.toString(),
  ]);

  autoTable(doc, {
    startY: serviceTableY + 5,
    head: [['Vessel', 'Capacity', 'From', 'To', 'Days']],
    body: tableBody,
    theme: 'striped',
    headStyles: { fillColor: [41, 128, 185], textColor: 255 },
    styles: { fontSize: 10 },
  });
  
  // Summary
  const summaryY = (doc as any).lastAutoTable.finalY + 10;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Summary of Service', 14, summaryY);
  autoTable(doc, {
      startY: summaryY + 5,
      body: [
          ['Total Days on Board:', `${totalDays} days`],
          ['Total Days At Sea:', `${totalSeaDays} days`],
          ['Total Days on Standby (in port/at anchor):', `${totalStandbyDays} days`],
      ],
      theme: 'plain',
      styles: { fontSize: 11 },
  });

  // Declaration
  const declarationY = (doc as any).lastAutoTable.finalY + 15;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(
    'I declare that the above information is a true and accurate record of this crew member’s service.',
    14,
    declarationY
  );
  
  // Signature Area
  const signatureY = declarationY + 30;
  doc.line(14, signatureY, 80, signatureY);
  doc.text('Master / Chief Engineer Signature', 14, signatureY + 5);

  doc.line(130, signatureY, 196, signatureY);
  doc.text('Date', 130, signatureY + 5);
  
  const shipStampY = signatureY + 20;
  doc.rect(130, shipStampY, 66, 25);
  doc.text('Ship\'s Stamp', 153, shipStampY + 13, { align: 'center'});


  // Footer
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text(
      `Generated by SeaJourney - Page ${i} of ${pageCount}`,
      105,
      287,
      { align: 'center' }
    );
  }

  // Open PDF in new tab
  doc.output('dataurlnewwindow');
}
