'use client';

import React, { useState, useMemo, useEffect, useRef } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { format, startOfDay, isAfter, parse, eachDayOfInterval, isWithinInterval, subMonths, addDays, differenceInDays } from 'date-fns';
import { LifeBuoy, Loader2, PlusCircle, Mail, Calendar, CalendarIcon, Ship, Clock, CheckCircle2, XCircle, FileText, Download, Trash2, AlertCircle, ChevronDown, ChevronUp } from 'lucide-react';

import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Separator } from '@/components/ui/separator';
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage, FormDescription } from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { SearchableSelect } from '@/components/ui/searchable-select';
import { Checkbox } from '@/components/ui/checkbox';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Calendar as CalendarComponent } from '@/components/ui/calendar';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger, DialogFooter } from '@/components/ui/dialog';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import { useUser, useSupabase } from '@/supabase';
import { useCollection, useDoc } from '@/supabase/database';
import { getVesselStateLogs, getVesselAssignments } from '@/supabase/database/queries';
import { calculateStandbyDays } from '@/lib/standby-calculation';
import { useToast } from '@/hooks/use-toast';
import { cn } from '@/lib/utils';
import { generateTestimonialPDF } from '@/lib/pdf-generator';
// testimonial_code is now auto-generated by database trigger when testimonial is approved
import type { Vessel, UserProfile, Testimonial, TestimonialStatus, VesselAssignment } from '@/lib/types';
import type { StateLog } from '@/lib/types';
import type { SupabaseClient } from '@supabase/supabase-js';

const testimonialSchema = z.object({
  vessel_id: z.string().min(1, 'Please select a vessel.'),
  start_date: z.date({ required_error: 'A start date is required.' }),
  end_date: z.date({ required_error: 'An end date is required.' }),
  captain_email: z.string().email('Please enter a valid email address.').optional().or(z.literal('')),
  captain_name: z.string().optional(),
  official_body: z.string().optional(),
  official_reference: z.string().optional(),
  notes: z.string().optional(),
}).refine((data) => {
  if (data.end_date && data.end_date < data.start_date) {
    return false;
  }
  return true;
}, {
  message: "End date must be after start date",
  path: ["end_date"],
}).refine((data) => {
  const today = startOfDay(new Date());
  const startDate = startOfDay(data.start_date);
  const endDate = startOfDay(data.end_date);
  
  if (isAfter(startDate, today) || isAfter(endDate, today)) {
    return false;
  }
  return true;
}, {
  message: "Dates cannot be in the future",
  path: ["end_date"],
});

type TestimonialFormValues = z.infer<typeof testimonialSchema>;

const APP_URL = process.env.NEXT_PUBLIC_APP_URL || 'http://www.seajourney.co.uk';

// Helper function to create or get a secure signoff token
async function createOrGetSignoffToken(
  supabase: SupabaseClient,
  testimonialId: string,
  captainEmail: string
): Promise<string> {
  // 1. Try to reuse a valid token if it exists
  const { data: existing, error: existingError } = await supabase
    .from('testimonials')
    .select('signoff_token, signoff_token_expires_at, signoff_target_email')
    .eq('id', testimonialId)
    .maybeSingle();

  if (existingError) {
    console.error('Error checking existing token:', existingError);
    throw existingError;
  }

  const now = new Date();

  if (
    existing?.signoff_token &&
    existing.signoff_token_expires_at &&
    existing.signoff_target_email === captainEmail &&
    new Date(existing.signoff_token_expires_at) > now
  ) {
    return existing.signoff_token as string;
  }

  // 2. Otherwise, create a new one
  const token = crypto.randomUUID(); // browser-safe in Next.js

  const expiresAt = new Date();
  expiresAt.setDate(expiresAt.getDate() + 7); // 7 days validity

  const { error: updateError } = await supabase
    .from('testimonials')
    .update({
      signoff_token: token,
      signoff_token_expires_at: expiresAt.toISOString(),
      signoff_target_email: captainEmail,
    })
    .eq('id', testimonialId);

  if (updateError) {
    console.error('Error creating signoff token:', updateError);
    throw updateError;
  }

  return token;
}

// Helper function to request captain signoff
async function requestCaptainSignoff(
  supabase: SupabaseClient,
  testimonial: Testimonial & { vessel_name?: string },
  toast: (props: { title: string; description: string; variant?: 'default' | 'destructive' }) => void
): Promise<void> {
  if (!testimonial.captain_email) {
    throw new Error('Captain email is required');
  }

  const captainEmail = testimonial.captain_email;
  const captainName = testimonial.captain_name || 'Captain';
  const vesselName = testimonial.vessel_name ?? 'Your Vessel';

  // 1. Ensure token is in DB
  const token = await createOrGetSignoffToken(
    supabase,
    testimonial.id,
    captainEmail
  );

  // 2. Build the link used in the email
  const signoffLink = `${APP_URL}/testimonials/signoff?token=${encodeURIComponent(
    token
  )}&email=${encodeURIComponent(captainEmail)}`;

  // 3. Call Edge Function
  const { data, error } = await supabase.functions.invoke('send-signoff-request', {
    body: {
      captainEmail,
      captainName,
      vesselName,
      signoffLink,
      pdfUrl: testimonial.pdf_url || null,
    },
  });

  if (error) {
    console.error('Error sending email:', error);
    
    // Try to get more details from the response
    if (error.context instanceof Response) {
      try {
        const errorText = await error.context.clone().text();
        console.error('Edge Function error response body:', errorText);
        try {
          const errorJson = JSON.parse(errorText);
          console.error('Edge Function error details:', errorJson);
        } catch {
          // Not JSON, that's fine
        }
      } catch (e) {
        console.error('Could not read error response body:', e);
      }
    }
    
    const statusCode = error.context?.status || error.status;
    const errorMessage = error.message || 'Unknown error';
    const isNetworkError = errorMessage?.includes('Failed to fetch') || 
                          errorMessage?.includes('Failed to send a request');
    
    let errorDescription = '';
    if (isNetworkError) {
      errorDescription = `Email function appears to be unavailable. Please verify the Edge Function 'send-signoff-request' is deployed in Supabase.`;
    } else if (statusCode === 400) {
      errorDescription = `The email request was invalid (Status: ${statusCode}). Please check the console for details and contact the captain manually.`;
    } else {
      errorDescription = statusCode 
        ? `Email failed (Status: ${statusCode}): ${errorMessage}. Please contact the captain manually.`
        : errorMessage 
          ? `Email failed: ${errorMessage}. Please contact the captain manually.`
          : `There was an error sending the email. Please contact the captain manually.`;
    }
    
    toast({
      title: 'Request Created',
      description: errorDescription,
      variant: statusCode === 400 ? 'destructive' : 'default',
    });
    
    return;
  }

  // 4. Optionally update status to pending_captain
  await supabase
    .from('testimonials')
    .update({ status: 'pending_captain' })
    .eq('id', testimonial.id);

  // 5. Show success toast
  toast({
    title: 'Request Sent',
    description: `Testimonial request has been sent to ${captainEmail}. You will be notified when the captain responds.`,
  });
}

// Helper function to calculate day counts from state logs for a date range
function calculateDayCounts(stateLogs: StateLog[], startDate: string, endDate: string) {
  const start = parse(startDate, 'yyyy-MM-dd', new Date());
  const end = parse(endDate, 'yyyy-MM-dd', new Date());
  
  console.log('[calculateDayCounts] Input:', {
    totalLogs: stateLogs.length,
    startDate,
    endDate,
    firstFewLogs: stateLogs.slice(0, 5).map(l => ({ date: l.date, state: l.state }))
  });
  
  // Filter logs to the date range (inclusive)
  const rangeLogs = stateLogs.filter(log => {
    const logDate = parse(log.date, 'yyyy-MM-dd', new Date());
    const isInRange = logDate >= start && logDate <= end;
    return isInRange;
  });
  
  console.log('[calculateDayCounts] Filtered logs in range:', {
    totalInRange: rangeLogs.length,
    firstFewInRange: rangeLogs.slice(0, 5).map(l => ({ date: l.date, state: l.state }))
  });
  
  // Calculate individual day counts
  const atSeaDays = rangeLogs.filter(log => log.state === 'underway').length;
  const yardDays = rangeLogs.filter(log => log.state === 'in-yard').length;
  const leaveDays = rangeLogs.filter(log => log.state === 'on-leave').length;
  
  // Calculate standby days using the standby calculation function
  // Standby includes 'at-anchor' and 'in-port' states
  const { totalStandbyDays } = calculateStandbyDays(rangeLogs);
  const standbyDays = totalStandbyDays;
  
  // Calculate total days as the sum to satisfy the database constraint
  // The constraint likely requires: total_days = at_sea_days + standby_days + yard_days + leave_days
  const totalDays = atSeaDays + standbyDays + yardDays + leaveDays;
  
  const result = {
    total_days: totalDays,
    at_sea_days: atSeaDays,
    standby_days: standbyDays,
    yard_days: yardDays,
    leave_days: leaveDays,
  };
  
  console.log('[calculateDayCounts] Result:', result);
  
  return result;
}

export default function TestimonialsPage() {
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [expandedTestimonials, setExpandedTestimonials] = useState<Set<string>>(new Set());
  const [isSaving, setIsSaving] = useState(false);
  const [testimonials, setTestimonials] = useState<Testimonial[]>([]);
  const [isLoadingTestimonials, setIsLoadingTestimonials] = useState(false);
  const [activeTab, setActiveTab] = useState<'all' | 'draft' | 'pending' | 'approved' | 'rejected'>('all');
  const [selectedVesselLogs, setSelectedVesselLogs] = useState<StateLog[]>([]);
  const [testimonialToDelete, setTestimonialToDelete] = useState<Testimonial | null>(null);
  const [isDeleting, setIsDeleting] = useState(false);

    const { user } = useUser();
  const { supabase } = useSupabase();
  const { toast } = useToast();

  const form = useForm<TestimonialFormValues>({
    resolver: zodResolver(testimonialSchema),
    defaultValues: {
      vessel_id: '',
      captain_email: '',
      captain_name: '',
      official_body: '',
      official_reference: '',
      notes: '',
    },
    mode: 'onChange',
  });

  // State to track if user wants to select a different vessel
  const [useDifferentVessel, setUseDifferentVessel] = useState(false);

  // Watch vessel_id and date range to calculate day counts
  const watchedVesselId = form.watch('vessel_id');
  const watchedStartDate = form.watch('start_date');
  const watchedEndDate = form.watch('end_date');
  
  // Track active captain for selected vessel (just the ID - profile fetched in inbox)
  const [activeCaptain, setActiveCaptain] = useState<{ id: string } | null>(null);
  const [isCheckingCaptain, setIsCheckingCaptain] = useState(false);

  // Fetch user profile
  const { data: userProfileRaw, isLoading: isLoadingProfile } = useDoc<UserProfile>('users', user?.id);
  
  const userProfile = useMemo(() => {
    if (!userProfileRaw) return null;
    return {
      ...userProfileRaw,
      id: userProfileRaw.id,
      email: (userProfileRaw as any).email || '',
      username: (userProfileRaw as any).username || '',
      activeVesselId: (userProfileRaw as any).active_vessel_id || (userProfileRaw as any).activeVesselId || undefined,
      firstName: (userProfileRaw as any).first_name || (userProfileRaw as any).firstName,
      lastName: (userProfileRaw as any).last_name || (userProfileRaw as any).lastName,
    } as UserProfile;
  }, [userProfileRaw]);

  // Query all vessels
  const { data: allVessels, isLoading: isLoadingVessels } = useCollection<Vessel>(
    user?.id ? 'vessels' : null,
    user?.id ? { orderBy: 'created_at', ascending: false } : undefined
  );

  // Filter vessels to only show ones the user has logged time on
  const [vesselStateLogs, setVesselStateLogs] = useState<Map<string, StateLog[]>>(new Map());

  useEffect(() => {
    if (allVessels && user?.id) {
      const fetchLogs = async () => {
        const newLogs = new Map<string, StateLog[]>();
        await Promise.all(allVessels.map(async (vessel) => {
          const logs = await getVesselStateLogs(supabase, vessel.id, user.id);
          if (logs && logs.length > 0) {
            newLogs.set(vessel.id, logs);
          }
        }));
        setVesselStateLogs(newLogs);
      };
      fetchLogs();
    }
  }, [allVessels, user?.id, supabase]);

  const vessels = useMemo(() => {
    if (!allVessels) return [];
    return allVessels.filter(vessel => {
      const logs = vesselStateLogs.get(vessel.id) || [];
      return logs.length > 0;
    });
  }, [allVessels, vesselStateLogs]);

  // Get current active vessel
  const currentVessel = useMemo(() => {
    if (!userProfile?.activeVesselId || !vessels.length) return null;
    return vessels.find(v => v.id === userProfile.activeVesselId) || null;
  }, [userProfile?.activeVesselId, vessels]);

  // Auto-select current vessel when dialog opens and trigger captain check
  useEffect(() => {
    if (isDialogOpen && currentVessel && !useDifferentVessel) {
      // Always set current vessel when dialog opens (unless user selected different)
      const currentValue = form.getValues('vessel_id');
      if (currentValue !== currentVessel.id) {
        form.setValue('vessel_id', currentVessel.id, { shouldValidate: false });
        console.log('[TESTIMONIALS] Auto-selected current vessel:', currentVessel.name);
      }
    }
  }, [isDialogOpen, currentVessel, useDifferentVessel, form]);

  // Also check for captain when current vessel is auto-selected
  useEffect(() => {
    if (isDialogOpen && currentVessel && !useDifferentVessel && watchedVesselId === currentVessel.id && !activeCaptain && !isCheckingCaptain) {
      // Trigger captain check by ensuring watchedVesselId is set
      // This will trigger the main captain check useEffect
      console.log('[TESTIMONIALS] Current vessel selected, captain check should trigger automatically');
    }
  }, [isDialogOpen, currentVessel, watchedVesselId, activeCaptain, isCheckingCaptain, useDifferentVessel]);

  // Reset form and useDifferentVessel when dialog closes
  useEffect(() => {
    if (!isDialogOpen) {
      // Small delay to allow dialog close animation
      setTimeout(() => {
        form.reset();
        setActiveCaptain(null);
        setUseDifferentVessel(false);
      }, 150);
    }
  }, [isDialogOpen, form]);

  // Fetch vessel assignments and state logs for selected vessel
  const [vesselAssignments, setVesselAssignments] = useState<VesselAssignment[]>([]);
  
  // Check for active captain when vessel is selected
  useEffect(() => {
    if (!watchedVesselId) {
      setActiveCaptain(null);
      form.setValue('captain_email', '', { shouldValidate: false });
      return;
    }

    let isCancelled = false;
    
    const checkActiveCaptain = async () => {
      setIsCheckingCaptain(true);
      console.log('[TESTIMONIALS] Checking for active captain for vessel:', watchedVesselId);
      
      try {
        // Check for active signing authority (primary captain) for this vessel
        // This is the source of truth for who can sign testimonials
        const { data: signingAuthority, error: signingAuthorityError } = await supabase
          .from('vessel_signing_authorities')
          .select('captain_user_id, is_primary')
          .eq('vessel_id', watchedVesselId)
          .eq('is_primary', true)
          .is('end_date', null)
          .limit(1)
          .maybeSingle();

        console.log('[TESTIMONIALS] Signing authority query result:', { signingAuthority, signingAuthorityError });

        if (isCancelled) return;

        if (signingAuthorityError) {
          console.error('[TESTIMONIALS] Error querying for signing authority:', {
            error: signingAuthorityError,
            code: signingAuthorityError.code,
            message: signingAuthorityError.message,
            details: signingAuthorityError.details,
            hint: signingAuthorityError.hint,
          });
          setActiveCaptain(null);
          form.setValue('captain_email', '', { shouldValidate: false });
          return;
        }

        if (!signingAuthority || !signingAuthority.captain_user_id) {
          console.log('[TESTIMONIALS] No active signing authority found for vessel:', {
            vesselId: watchedVesselId,
            signingAuthority: signingAuthority,
            hasCaptainUserId: !!signingAuthority?.captain_user_id
          });
          setActiveCaptain(null);
          form.setValue('captain_email', '', { shouldValidate: false });
          return;
        }

        console.log('[TESTIMONIALS] Found signing authority:', {
          vesselId: watchedVesselId,
          captainUserId: signingAuthority.captain_user_id,
          isPrimary: signingAuthority.is_primary
        });

        if (isCancelled) return;

        // We only need the captain's user ID - no need to fetch profile
        // The captain's info can be fetched when they view their inbox
        console.log('[TESTIMONIALS] Active captain found - user ID:', signingAuthority.captain_user_id);

        // Set active captain with just the ID - profile will be fetched when captain views inbox
        setActiveCaptain({
          id: signingAuthority.captain_user_id,
        });

        // Don't set captain_email - we're using captain_user_id for inbox matching
        form.setValue('captain_email', '', { shouldValidate: false });
        console.log('[TESTIMONIALS] Using captain_user_id for inbox matching, no email needed');
      } catch (error) {
        if (isCancelled) return;
        console.error('[TESTIMONIALS] Error checking for active captain:', error);
        setActiveCaptain(null);
        form.setValue('captain_email', '', { shouldValidate: false });
      } finally {
        if (!isCancelled) {
          setIsCheckingCaptain(false);
        }
      }
    };

    checkActiveCaptain();

    return () => {
      isCancelled = true;
    };
  }, [watchedVesselId, supabase, form]);
  
  useEffect(() => {
    if (watchedVesselId && user?.id) {
      // Use ref to track previous assignments for polling comparison
      const previousAssignmentsRef = useRef<VesselAssignment[]>([]);
      
      const fetchData = async () => {
        console.log('[TESTIMONIALS] Fetching logs for vessel:', {
          vesselId: watchedVesselId,
          userId: user.id
        });
        
        try {
          const [logs, assignments] = await Promise.all([
            getVesselStateLogs(supabase, watchedVesselId, user.id),
            getVesselAssignments(supabase, user.id)
          ]);
          
          console.log('[TESTIMONIALS] Fetched logs:', {
            count: logs.length,
            firstFew: logs.slice(0, 5).map(l => ({ date: l.date, state: l.state }))
          });
          
          setSelectedVesselLogs(logs);
          
          // Filter assignments for this vessel
          const vesselAssignments = assignments.filter(a => a.vesselId === watchedVesselId);
          setVesselAssignments(vesselAssignments);
          previousAssignmentsRef.current = [...vesselAssignments];
        } catch (error) {
          console.error('[TESTIMONIALS] Error fetching logs:', error);
          setSelectedVesselLogs([]);
          setVesselAssignments([]);
          previousAssignmentsRef.current = [];
        }
      };
      fetchData();

      // Set up real-time subscription to detect changes to vessel assignments
      // This will detect changes made from the mobile app or other sources
      const channel = supabase
        .channel(`testimonials-vessel-assignments-${user.id}-${Date.now()}`)
        .on(
          'postgres_changes',
          {
            event: '*', // INSERT, UPDATE, DELETE
            schema: 'public',
            table: 'vessel_assignments',
            filter: `user_id=eq.${user.id}`,
          },
          async (payload) => {
            console.log('[TESTIMONIALS] Vessel assignment changed via real-time:', payload);
            // Refetch assignments when changes are detected
            try {
              const assignments = await getVesselAssignments(supabase, user.id);
              const vesselAssignments = assignments.filter(a => a.vesselId === watchedVesselId);
              setVesselAssignments(vesselAssignments);
              previousAssignmentsRef.current = [...vesselAssignments];
            } catch (error) {
              console.error('[TESTIMONIALS] Error refetching assignments after change:', error);
            }
          }
        )
        .subscribe((status) => {
          console.log('[TESTIMONIALS] Real-time subscription status:', status);
          if (status === 'SUBSCRIBED') {
            console.log('[TESTIMONIALS] Successfully subscribed to vessel_assignments changes');
          } else if (status === 'CHANNEL_ERROR') {
            console.error('[TESTIMONIALS] Real-time subscription error - falling back to polling');
          }
        });

      // Fallback: Poll for changes every 3 seconds if real-time doesn't work
      // This ensures we detect changes even if real-time subscriptions fail
      const pollInterval = setInterval(async () => {
        try {
          const assignments = await getVesselAssignments(supabase, user.id);
          const vesselAssignments = assignments.filter(a => a.vesselId === watchedVesselId);
          
          // Check if assignments have changed by comparing end_date values
          // Use a more robust comparison
          const previous = previousAssignmentsRef.current;
          const previousMap = new Map(previous.map(a => [a.id, a]));
          const currentMap = new Map(vesselAssignments.map(a => [a.id, a]));
          
          const hasChanges = 
            vesselAssignments.length !== previous.length ||
            vesselAssignments.some(a => {
              const prev = previousMap.get(a.id);
              return !prev || 
                a.vesselId !== prev.vesselId ||
                a.startDate !== prev.startDate || 
                a.endDate !== prev.endDate;
            }) ||
            previous.some(a => !currentMap.has(a.id));
          
          if (hasChanges) {
            console.log('[TESTIMONIALS] Polling detected changes in vessel assignments', {
              previous: previous.map(a => ({ id: a.id, vesselId: a.vesselId, startDate: a.startDate, endDate: a.endDate })),
              current: vesselAssignments.map(a => ({ id: a.id, vesselId: a.vesselId, startDate: a.startDate, endDate: a.endDate }))
            });
            setVesselAssignments(vesselAssignments);
            previousAssignmentsRef.current = [...vesselAssignments];
          }
        } catch (error) {
          console.error('[TESTIMONIALS] Error polling vessel assignments:', error);
        }
      }, 3000); // Poll every 3 seconds (more frequent)

      return () => {
        supabase.removeChannel(channel);
        clearInterval(pollInterval);
      };
    } else {
      setSelectedVesselLogs([]);
      setVesselAssignments([]);
    }
  }, [watchedVesselId, user?.id, supabase]);

  // Calculate date range options based on vessel assignments and state logs
  const dateRangeOptions = useMemo(() => {
    // Only require vessel and logs - assignments are optional
    if (!watchedVesselId || selectedVesselLogs.length === 0) {
      return [];
    }

    const today = startOfDay(new Date());
    const options: Array<{ label: string; startDate: Date; endDate: Date }> = [];

    // Option 1: Period between last two leave periods (or before last leave if only one)
    // Find all unique leave dates (group consecutive leave days)
    const allLeaveDates = selectedVesselLogs
      .filter(log => log.state === 'on-leave')
      .map(log => parse(log.date, 'yyyy-MM-dd', new Date()))
      .sort((a, b) => a.getTime() - b.getTime());

    // Group consecutive leave dates into periods
    const leavePeriods: Array<{ start: Date; end: Date }> = [];
    if (allLeaveDates.length > 0) {
      let currentPeriodStart = allLeaveDates[0];
      let currentPeriodEnd = allLeaveDates[0];
      
      for (let i = 1; i < allLeaveDates.length; i++) {
        const daysDiff = differenceInDays(allLeaveDates[i], currentPeriodEnd);
        if (daysDiff <= 1) {
          // Consecutive or same day - extend current period
          currentPeriodEnd = allLeaveDates[i];
        } else {
          // Gap found - save current period and start new one
          leavePeriods.push({ start: currentPeriodStart, end: currentPeriodEnd });
          currentPeriodStart = allLeaveDates[i];
          currentPeriodEnd = allLeaveDates[i];
        }
      }
      // Add the last period
      leavePeriods.push({ start: currentPeriodStart, end: currentPeriodEnd });
    }

    if (leavePeriods.length >= 2) {
      // We have at least 2 leave periods - find onboard period between the last two
      const lastLeavePeriod = leavePeriods[leavePeriods.length - 1];
      const previousLeavePeriod = leavePeriods[leavePeriods.length - 2];
      
      // Find logged dates between the two leave periods (onboard period)
      const onboardDatesBetweenLeaves = selectedVesselLogs
        .filter(log => {
          const logDate = parse(log.date, 'yyyy-MM-dd', new Date());
          return logDate > previousLeavePeriod.end && logDate < lastLeavePeriod.start && log.state !== 'on-leave';
        })
        .map(log => parse(log.date, 'yyyy-MM-dd', new Date()))
        .sort((a, b) => a.getTime() - b.getTime());

      if (onboardDatesBetweenLeaves.length > 0) {
        const periodStart = onboardDatesBetweenLeaves[0];
        const periodEnd = onboardDatesBetweenLeaves[onboardDatesBetweenLeaves.length - 1];
        
        options.push({
          label: 'Between Last Two Leaves',
          startDate: periodStart,
          endDate: periodEnd,
        });
      }
    } else if (leavePeriods.length === 1) {
      // Only one leave period - find period before it
      const lastLeavePeriod = leavePeriods[0];
      
      // Find logged dates before the last leave
      const onboardDatesBeforeLeave = selectedVesselLogs
        .filter(log => {
          const logDate = parse(log.date, 'yyyy-MM-dd', new Date());
          return logDate < lastLeavePeriod.start && log.state !== 'on-leave';
        })
        .map(log => parse(log.date, 'yyyy-MM-dd', new Date()))
        .sort((a, b) => a.getTime() - b.getTime());

      if (onboardDatesBeforeLeave.length > 0) {
        const periodStart = onboardDatesBeforeLeave[0];
        const periodEnd = onboardDatesBeforeLeave[onboardDatesBeforeLeave.length - 1];
        
        options.push({
          label: 'Before Last Leave',
          startDate: periodStart,
          endDate: periodEnd,
        });
      }
    }

    // Option 2: Fixed time period options (Last 2, 3, 4 months)
    const twoMonthsAgo = subMonths(today, 2);
    const threeMonthsAgo = subMonths(today, 3);
    const fourMonthsAgo = subMonths(today, 4);

    // Check if we have logs in each period
    const hasLogsLast2Months = selectedVesselLogs.some(log => {
      const logDate = parse(log.date, 'yyyy-MM-dd', new Date());
      return logDate >= twoMonthsAgo;
    });

    const hasLogsLast3Months = selectedVesselLogs.some(log => {
      const logDate = parse(log.date, 'yyyy-MM-dd', new Date());
      return logDate >= threeMonthsAgo;
    });

    const hasLogsLast4Months = selectedVesselLogs.some(log => {
      const logDate = parse(log.date, 'yyyy-MM-dd', new Date());
      return logDate >= fourMonthsAgo;
    });

    if (hasLogsLast2Months) {
      options.push({
        label: 'Last 2 Months',
        startDate: twoMonthsAgo,
        endDate: today,
      });
    }

    if (hasLogsLast3Months) {
      options.push({
        label: 'Last 3 Months',
        startDate: threeMonthsAgo,
        endDate: today,
      });
    }

    if (hasLogsLast4Months) {
      options.push({
        label: 'Last 4 Months',
        startDate: fourMonthsAgo,
        endDate: today,
      });
    }


    return options;
  }, [watchedVesselId, vesselAssignments, selectedVesselLogs]);

  // Function to apply a date range option
  const applyDateRangeOption = (option: { startDate: Date; endDate: Date }) => {
    form.setValue('start_date', startOfDay(option.startDate));
    form.setValue('end_date', startOfDay(option.endDate));
  };

  // Calculate and display day counts preview
  const dayCountsPreview = useMemo(() => {
    if (!watchedStartDate || !watchedEndDate || selectedVesselLogs.length === 0) {
      return null;
    }

    const startDateStr = format(watchedStartDate, 'yyyy-MM-dd');
    const endDateStr = format(watchedEndDate, 'yyyy-MM-dd');
    
    return calculateDayCounts(selectedVesselLogs, startDateStr, endDateStr);
  }, [watchedStartDate, watchedEndDate, selectedVesselLogs]);

  // Fetch testimonials
  useEffect(() => {
    if (!user?.id) return;

    setIsLoadingTestimonials(true);
    const fetchTestimonials = async () => {
      try {
        const { data, error } = await supabase
          .from('testimonials')
          .select('*')
          .eq('user_id', user.id)
          .order('created_at', { ascending: false });

        if (error) {
          console.error('Error fetching testimonials:', error);
          setTestimonials([]);
        } else {
          setTestimonials((data || []) as Testimonial[]);
        }
      } catch (error) {
        console.error('Error fetching testimonials:', error);
        setTestimonials([]);
      } finally {
        setIsLoadingTestimonials(false);
      }
    };

    fetchTestimonials();
  }, [user?.id, supabase]);

  const handleSubmit = async (data: TestimonialFormValues) => {
    if (!user?.id) return;

    setIsSaving(true);
    try {
      const startDateStr = format(data.start_date, 'yyyy-MM-dd');
      const endDateStr = format(data.end_date, 'yyyy-MM-dd');

      // Always fetch fresh logs to ensure we have the latest data
      // This ensures logs are available even if dates were manually selected before logs finished loading
      console.log('[TESTIMONIALS] Fetching logs for submission:', {
        vesselId: data.vessel_id,
        userId: user.id,
        selectedVesselLogsCount: selectedVesselLogs.length
      });
      
      let logsToUse: StateLog[];
      try {
        logsToUse = await getVesselStateLogs(supabase, data.vessel_id, user.id);
        console.log('[TESTIMONIALS] Fetched logs for submission:', {
          count: logsToUse.length,
          firstFew: logsToUse.slice(0, 5).map(l => ({ date: l.date, state: l.state }))
        });
        
        // Update selectedVesselLogs state for UI consistency
        if (logsToUse.length > 0) {
          setSelectedVesselLogs(logsToUse);
        }
      } catch (error: any) {
        console.error('[TESTIMONIALS] Error fetching logs for submission:', {
          error,
          message: error?.message,
          code: error?.code,
          details: error?.details
        });
        toast({
          title: 'Error',
          description: error?.message || 'Failed to fetch vessel logs. Please ensure you have logged time on this vessel.',
          variant: 'destructive',
        });
        setIsSaving(false);
        return;
      }
      
      if (!logsToUse || logsToUse.length === 0) {
        toast({
          title: 'No Logs Found',
          description: 'No logged dates found for this vessel. Please ensure you have logged time on this vessel before requesting a testimonial.',
          variant: 'destructive',
        });
        setIsSaving(false);
        return;
      }

      console.log('[TESTIMONIALS] Calculating day counts with logs:', {
        logCount: logsToUse.length,
        dateRange: { start: startDateStr, end: endDateStr },
        logsInRange: logsToUse.filter(log => {
          const logDate = parse(log.date, 'yyyy-MM-dd', new Date());
          const start = parse(startDateStr, 'yyyy-MM-dd', new Date());
          const end = parse(endDateStr, 'yyyy-MM-dd', new Date());
          return logDate >= start && logDate <= end;
        }).length
      });

      // Calculate day counts
      const dayCounts = calculateDayCounts(logsToUse, startDateStr, endDateStr);
      
      console.log('[TESTIMONIALS] Calculated day counts:', dayCounts);

      // Validate that total_days equals the sum (required by database constraint)
      const calculatedTotal = dayCounts.at_sea_days + dayCounts.standby_days + dayCounts.yard_days + dayCounts.leave_days;
      if (dayCounts.total_days !== calculatedTotal) {
        console.warn('Day counts mismatch, adjusting total_days:', {
          original: dayCounts.total_days,
          calculated: calculatedTotal,
          dayCounts,
        });
        dayCounts.total_days = calculatedTotal;
      }

      // Determine initial status: if captain_email is provided, status is 'pending_captain', otherwise 'draft'
      const initialStatus: TestimonialStatus = data.captain_email ? 'pending_captain' : 'draft';

      // Determine captain_user_id and captain_email
      // If activeCaptain is found (SeaJourney user), use their user_id
      // Otherwise, use the email provided by the user for external captains
      const captainUserId = activeCaptain?.id || null;
      const captainEmail = captainUserId ? null : (data.captain_email || null); // Only use email for external captains
      const captainName = data.captain_name || null; // Optional name field

      // If we have an active captain (SeaJourney user), set status to pending_captain
      // They will see it in their inbox automatically
      const finalStatus: TestimonialStatus = captainUserId ? 'pending_captain' : initialStatus;

      // Create testimonial (testimonial_code will be auto-generated by database trigger when approved)
      const result = await supabase
        .from('testimonials')
        .insert({
          user_id: user.id,
          vessel_id: data.vessel_id,
          start_date: startDateStr,
          end_date: endDateStr,
          total_days: dayCounts.total_days,
          at_sea_days: dayCounts.at_sea_days,
          standby_days: dayCounts.standby_days,
          yard_days: dayCounts.yard_days,
          leave_days: dayCounts.leave_days,
          status: finalStatus,
          captain_user_id: captainUserId,
          captain_email: captainEmail,
          captain_name: captainName,
          official_body: data.official_body || null,
          official_reference: data.official_reference || null,
          notes: data.notes || null,
          // testimonial_code is NOT set here - it will be auto-generated by database trigger when status changes to 'approved'
        })
        .select()
        .single();

      if (result.error) {
        throw result.error;
      }

      const testimonialData = result.data;

      // Send email to captain if captain_email is provided AND there's no active captain (SeaJourney user)
      // If there's an active captain (captain_user_id), the testimonial will appear in their inbox automatically
      if (captainEmail && finalStatus === 'pending_captain' && !captainUserId) {
        // External captain (not a SeaJourney user) - send email
        const vesselName = vessels.find(v => v.id === data.vessel_id)?.name || 'Unknown Vessel';
        
        await requestCaptainSignoff(
          supabase,
          {
            ...testimonialData,
            vessel_name: vesselName,
          },
          toast
        );
      } else if (captainUserId) {
        // Active SeaJourney captain found - testimonial goes to inbox automatically, no email needed
        toast({
          title: 'Testimonial Request Sent',
          description: 'Your testimonial request has been sent to the captain\'s inbox. They will be notified.',
        });
      } else {
        toast({
          title: 'Testimonial Created',
          description: 'Testimonial has been saved as draft. You can edit it later or send it to a captain.',
        });
      }


      form.reset();
      setActiveCaptain(null); // Clear active captain when dialog closes
      setIsDialogOpen(false);
      
      // Refresh testimonials list
      const { data: updatedData } = await supabase
        .from('testimonials')
        .select('*')
        .eq('user_id', user.id)
        .order('created_at', { ascending: false });
      
      if (updatedData) {
        setTestimonials(updatedData as Testimonial[]);
      }
    } catch (error: any) {
      console.error('Error creating testimonial:', error);
      toast({
        title: 'Error',
        description: error.message || 'Failed to create testimonial. Please try again.',
        variant: 'destructive',
      });
    } finally {
      setIsSaving(false);
    }
  };

  const filteredTestimonials = useMemo(() => {
    if (activeTab === 'all') return testimonials;
    if (activeTab === 'pending') {
      // Show both pending_captain and pending_official when 'pending' is selected
      return testimonials.filter(t => t.status === 'pending_captain' || t.status === 'pending_official');
    }
    return testimonials.filter(t => t.status === activeTab);
  }, [testimonials, activeTab]);

  const getVesselName = (vesselId: string) => {
    return vessels.find(v => v.id === vesselId)?.name || 'Unknown Vessel';
  };

  const getVesselDetails = (vesselId: string) => {
    return vessels.find(v => v.id === vesselId);
  };

  const handleGeneratePDF = async (testimonial: Testimonial) => {
    if (!userProfile) {
      toast({
        title: 'Error',
        description: 'User profile not loaded.',
        variant: 'destructive',
      });
      return;
    }

    const vessel = getVesselDetails(testimonial.vessel_id);
    if (!vessel) {
      toast({
        title: 'Error',
        description: 'Vessel details not found.',
        variant: 'destructive',
      });
      return;
    }

    // Fetch captain profile if captain_user_id is available
    let captainProfile = null;
    if (testimonial.captain_user_id) {
      try {
        console.log('[PDF GENERATION] Fetching captain profile for user_id:', testimonial.captain_user_id);
        const { data: captainData, error: captainError } = await supabase
          .from('users')
          .select('first_name, last_name, position, email')
          .eq('id', testimonial.captain_user_id)
          .maybeSingle();

        if (captainError) {
          console.error('[PDF GENERATION] Error fetching captain profile:', captainError);
        } else if (captainData) {
          console.log('[PDF GENERATION] Captain profile fetched:', captainData);
          captainProfile = {
            firstName: captainData.first_name || undefined,
            lastName: captainData.last_name || undefined,
            position: captainData.position || null,
            email: captainData.email || undefined,
          };
        } else {
          console.log('[PDF GENERATION] No captain profile found for user_id:', testimonial.captain_user_id);
        }
      } catch (error) {
        console.error('[PDF GENERATION] Exception fetching captain profile:', error);
        // Continue without captain profile - will use testimonial.captain_name/email
      }
    } else {
      console.log('[PDF GENERATION] No captain_user_id, using testimonial.captain_name/email:', {
        captain_name: testimonial.captain_name,
        captain_email: testimonial.captain_email
      });
    }

    try {
      await generateTestimonialPDF({
      testimonial: {
        id: testimonial.id,
        start_date: testimonial.start_date,
        end_date: testimonial.end_date,
        total_days: testimonial.total_days,
        at_sea_days: testimonial.at_sea_days,
        standby_days: testimonial.standby_days,
        yard_days: testimonial.yard_days,
        leave_days: testimonial.leave_days,
        captain_name: testimonial.captain_name,
        captain_email: testimonial.captain_email,
        captain_position: (testimonial as any).captain_position || null,
        official_body: testimonial.official_body,
        official_reference: testimonial.official_reference,
        notes: testimonial.notes,
        testimonial_code: testimonial.testimonial_code,
        status: testimonial.status,
        signoff_used_at: testimonial.signoff_used_at,
        created_at: testimonial.created_at,
        updated_at: testimonial.updated_at,
      },
      userProfile: {
        firstName: userProfile.firstName,
        lastName: userProfile.lastName,
        username: userProfile.username,
        email: userProfile.email || '',
        dateOfBirth: null, // Not available in current user profile
        position: userProfile.position || null,
      },
      vessel: {
        name: vessel.name,
        type: vessel.type || null,
        officialNumber: vessel.officialNumber || null,
        flag_state: vessel.flag_state || null,
        length_m: vessel.length_m || null,
        gross_tonnage: vessel.gross_tonnage || null,
        call_sign: vessel.call_sign || null,
      },
      captainProfile: captainProfile,
    });
    } catch (error) {
      console.error('Error generating PDF:', error);
      toast({
        title: 'Error',
        description: 'Failed to generate PDF. Please try again.',
        variant: 'destructive',
      });
    }
  };

  const handleDeleteTestimonial = async (testimonial: Testimonial) => {
    if (!user?.id) {
      toast({
        title: 'Error',
        description: 'You must be logged in to delete testimonials.',
        variant: 'destructive',
      });
      return;
    }

    setIsDeleting(true);
    try {
      console.log('Attempting to delete testimonial:', testimonial.id);
      console.log('Current user ID:', user.id);
      
      // Delete the testimonial - RLS will automatically check user_id
      // Using .select() to get confirmation of what was deleted
      const { data: deletedData, error: deleteError } = await supabase
        .from('testimonials')
        .delete()
        .eq('id', testimonial.id)
        .select();

      console.log('Delete response:', { deletedData, deleteError });

      if (deleteError) {
        console.error('Delete error details:', {
          code: deleteError.code,
          message: deleteError.message,
          details: deleteError.details,
          hint: deleteError.hint,
        });
        throw deleteError;
      }

      // Check if anything was actually deleted
      if (!deletedData || deletedData.length === 0) {
        throw new Error('No testimonial was deleted. It may not exist or you may not have permission.');
      }

      console.log('Successfully deleted testimonial:', deletedData);

      // Remove from local state immediately for better UX
      setTestimonials((prev) => prev.filter((t) => t.id !== testimonial.id));

      toast({
        title: 'Testimonial Deleted',
        description: 'The testimonial has been successfully deleted.',
      });

      // Refresh testimonials list to ensure consistency
      const { data: updatedData, error: refreshError } = await supabase
        .from('testimonials')
        .select('*')
        .eq('user_id', user.id)
        .order('created_at', { ascending: false });

      if (refreshError) {
        console.error('Refresh error (non-critical):', refreshError);
      } else if (updatedData) {
        setTestimonials(updatedData as Testimonial[]);
      }

      setTestimonialToDelete(null);
    } catch (error: any) {
      console.error('Error deleting testimonial:', error);
      console.error('Full error object:', JSON.stringify(error, null, 2));
      
      let errorMessage = 'Failed to delete testimonial. Please try again.';
      
      if (error?.message) {
        errorMessage = error.message;
      } else if (error?.code === 'PGRST116') {
        errorMessage = 'No rows were deleted. You may not have permission to delete this testimonial.';
      } else if (error?.code === '42501') {
        errorMessage = 'Permission denied. You do not have permission to delete this testimonial.';
      } else if (error?.code) {
        errorMessage = `Delete failed: ${error.code}. ${error.message || 'Please check the console for details.'}`;
      }

      toast({
        title: 'Error',
        description: errorMessage,
        variant: 'destructive',
      });
    } finally {
      setIsDeleting(false);
    }
  };

  const getStatusBadge = (status: TestimonialStatus) => {
    switch (status) {
      case 'draft':
        return <Badge variant="outline" className="bg-gray-500/10 text-gray-700 dark:text-gray-400 border-gray-500/20"><FileText className="mr-1 h-3 w-3" />Draft</Badge>;
      case 'pending_captain':
        return <Badge variant="outline" className="bg-yellow-500/10 text-yellow-700 dark:text-yellow-400 border-yellow-500/20"><Clock className="mr-1 h-3 w-3" />Pending Captain</Badge>;
      case 'pending_official':
        return <Badge variant="outline" className="bg-blue-500/10 text-blue-700 dark:text-blue-400 border-blue-500/20"><Clock className="mr-1 h-3 w-3" />Pending Official</Badge>;
      case 'approved':
        return <Badge variant="outline" className="bg-green-500/10 text-green-700 dark:text-green-400 border-green-500/20"><CheckCircle2 className="mr-1 h-3 w-3" />Approved</Badge>;
      case 'rejected':
        return <Badge variant="outline" className="bg-red-500/10 text-red-700 dark:text-red-400 border-red-500/20"><XCircle className="mr-1 h-3 w-3" />Rejected</Badge>;
    }
  };

  const isLoading = isLoadingProfile || isLoadingVessels || isLoadingTestimonials;

    return (
    <div className="flex flex-col gap-6">
      {/* Header Section */}
      <div className="space-y-2">
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
          <div className="space-y-1">
            <h1 className="text-3xl font-bold tracking-tight">Testimonials</h1>
            <p className="text-muted-foreground">
              Request testimonials from vessel captains and view your testimonial requests.
            </p>
                </div>
          <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
            <DialogTrigger asChild>
              <Button className="rounded-xl">
                <PlusCircle className="mr-2 h-4 w-4" />
                Request Testimonial
              </Button>
            </DialogTrigger>
            <DialogContent className="rounded-xl max-w-2xl max-h-[90vh] overflow-y-auto">
              <DialogHeader>
                <DialogTitle>Request Testimonial</DialogTitle>
              </DialogHeader>
              <Form {...form}>
                <form onSubmit={form.handleSubmit(handleSubmit)} className="space-y-4">
                  {/* Show current vessel info if available */}
                  {currentVessel && !useDifferentVessel && (
                    <Card className="border-primary/30 bg-gradient-to-br from-primary/5 to-primary/10">
                      <CardContent className="pt-6">
                        <div className="flex items-start justify-between gap-4">
                          <div className="flex items-start gap-3 w-full">
                            <div className="h-10 w-10 rounded-lg bg-primary/20 flex items-center justify-center border border-primary/30 shrink-0">
                              <Ship className="h-5 w-5 text-primary" />
                            </div>
                            <div className="flex-1 min-w-0">
                              <h3 className="text-sm font-semibold">Current Vessel</h3>
                              <p className="text-lg font-medium mt-1">{currentVessel.name}</p>
                              <p className="text-xs text-muted-foreground mt-1">
                                {currentVessel.type} • {currentVessel.officialNumber || 'No IMO'}
                              </p>
                              
                              {/* Captain Info */}
                              <div className="mt-3 pt-3 border-t border-primary/20">
                                {isCheckingCaptain ? (
                                  <div className="flex items-center gap-2 text-xs text-muted-foreground">
                                    <Loader2 className="h-3 w-3 animate-spin" />
                                    <span>Checking for active captain...</span>
                                  </div>
                                ) : activeCaptain ? (
                                  <div className="space-y-1">
                                    <div className="flex items-center gap-2">
                                      <Badge variant="outline" className="text-xs bg-green-500/10 text-green-700 border-green-500/20 dark:bg-green-500/20 dark:text-green-400">
                                        <CheckCircle2 className="h-3 w-3 mr-1" />
                                        Active Captain Found
                                      </Badge>
                                    </div>
                                    <p className="text-xs text-muted-foreground mt-1 italic">
                                      Your request will be sent directly to this captain's inbox
                                    </p>
                                  </div>
                                ) : (
                                  <div className="text-xs text-muted-foreground">
                                    <Badge variant="outline" className="text-xs">
                                      No active captain found
                                    </Badge>
                                    <p className="mt-1">You can enter a captain email manually below</p>
                                  </div>
                                )}
                              </div>
                            </div>
                          </div>
                        </div>
                      </CardContent>
                    </Card>
                  )}

                  {/* Option to select different vessel */}
                  {currentVessel && (
                    <div className="flex items-center space-x-2 pb-2">
                      <Checkbox
                        id="use-different-vessel"
                        checked={useDifferentVessel}
                        onCheckedChange={(checked) => {
                          setUseDifferentVessel(checked as boolean);
                          if (!checked && currentVessel) {
                            // Reset to current vessel
                            form.setValue('vessel_id', currentVessel.id, { shouldValidate: false });
                          } else {
                            // Clear selection so user can choose
                            form.setValue('vessel_id', '', { shouldValidate: false });
                          }
                        }}
                      />
                      <label
                        htmlFor="use-different-vessel"
                        className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70 cursor-pointer"
                      >
                        Select a different vessel
                      </label>
                    </div>
                  )}

                  {/* Vessel selector - always rendered but hidden when using current vessel */}
                  <FormField
                    control={form.control}
                    name="vessel_id"
                    render={({ field }) => (
                      <FormItem className={currentVessel && !useDifferentVessel ? 'sr-only' : ''}>
                        <FormLabel>Vessel</FormLabel>
                        <FormControl>
                          <SearchableSelect
                            options={vessels.map(vessel => ({
                              value: vessel.id,
                              label: vessel.name,
                            }))}
                            value={field.value || ''}
                            onValueChange={field.onChange}
                            placeholder="Select a vessel..."
                          />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />


                  {/* Quick Date Range Options */}
                  {watchedVesselId && (
                    <div className="space-y-3">
                      <FormLabel className="text-base font-semibold">Quick Select Date Range</FormLabel>
                      {dateRangeOptions && dateRangeOptions.length > 0 ? (
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                          {dateRangeOptions.map((option, index) => {
                            const daysDiff = differenceInDays(option.endDate, option.startDate) + 1;
                            return (
                              <button
                                key={index}
                                type="button"
                                onClick={() => applyDateRangeOption(option)}
                                className="group relative rounded-xl border-2 border-border bg-card p-4 text-left hover:border-primary hover:bg-accent transition-all hover:shadow-md"
                              >
                                <div className="flex items-start justify-between gap-3">
                                  <div className="flex-1 min-w-0">
                                    <div className="font-semibold text-sm mb-1.5 group-hover:text-primary transition-colors">
                                      {option.label}
                                    </div>
                                    <div className="flex flex-col gap-1 text-xs text-muted-foreground">
                                      <div className="flex items-center gap-1.5">
                                        <CalendarIcon className="h-3.5 w-3.5" />
                                        <span>{format(option.startDate, 'MMM d, yyyy')}</span>
                                      </div>
                                      <div className="flex items-center gap-1.5">
                                        <CalendarIcon className="h-3.5 w-3.5" />
                                        <span>{format(option.endDate, 'MMM d, yyyy')}</span>
                                      </div>
                                    </div>
                                  </div>
                                  <div className="flex-shrink-0 text-right">
                                    <div className="text-lg font-bold text-primary">
                                      {daysDiff}
                                    </div>
                                    <div className="text-xs text-muted-foreground">
                                      {daysDiff === 1 ? 'day' : 'days'}
                                    </div>
                                  </div>
                                </div>
                              </button>
                            );
                          })}
                        </div>
                      ) : selectedVesselLogs.length === 0 ? (
                        <div className="rounded-lg border border-dashed p-4 text-center">
                          <p className="text-sm text-muted-foreground">
                            Loading vessel data...
                          </p>
                        </div>
                      ) : (
                        <div className="rounded-lg border border-dashed p-4 text-center">
                          <p className="text-sm text-muted-foreground">
                            No date range options available. Ensure you have logged time on this vessel.
                          </p>
                        </div>
                      )}
                    </div>
                  )}

                  <div className="grid grid-cols-2 gap-4">
                    <FormField
                      control={form.control}
                      name="start_date"
                      render={({ field }) => (
                        <FormItem className="flex flex-col">
                          <FormLabel>Start Date</FormLabel>
                          <Popover>
                            <PopoverTrigger asChild>
                              <FormControl>
                                <Button
                                  variant="outline"
                                  className={cn(
                                    "w-full rounded-xl justify-start text-left font-normal",
                                    !field.value && "text-muted-foreground"
                                  )}
                                >
                                  <CalendarIcon className="mr-2 h-4 w-4" />
                                  {field.value ? format(field.value, 'PPP') : 'Pick a date'}
                                </Button>
                              </FormControl>
                            </PopoverTrigger>
                            <PopoverContent className="w-auto p-0" align="start">
                              <CalendarComponent
                                mode="single"
                                selected={field.value}
                                onSelect={field.onChange}
                                disabled={(date) => isAfter(date, startOfDay(new Date()))}
                                initialFocus
                              />
                            </PopoverContent>
                          </Popover>
                          <FormMessage />
                        </FormItem>
                      )}
                    />

                    <FormField
                      control={form.control}
                      name="end_date"
                      render={({ field }) => (
                        <FormItem className="flex flex-col">
                          <FormLabel>End Date</FormLabel>
                          <Popover>
                            <PopoverTrigger asChild>
                              <FormControl>
                                <Button
                                  variant="outline"
                                  className={cn(
                                    "w-full rounded-xl justify-start text-left font-normal",
                                    !field.value && "text-muted-foreground"
                                  )}
                                >
                                  <CalendarIcon className="mr-2 h-4 w-4" />
                                  {field.value ? format(field.value, 'PPP') : 'Pick a date'}
                                </Button>
                              </FormControl>
                            </PopoverTrigger>
                            <PopoverContent className="w-auto p-0" align="start">
                              <CalendarComponent
                                mode="single"
                                selected={field.value}
                                onSelect={field.onChange}
                                disabled={(date) => isAfter(date, startOfDay(new Date())) || (form.watch('start_date') && date < form.watch('start_date'))}
                                initialFocus
                              />
                            </PopoverContent>
                          </Popover>
                          <FormMessage />
                        </FormItem>
                      )}
                    />
            </div>

                  {/* Day Counts Preview */}
                  {dayCountsPreview && (
                    <div className="p-4 bg-muted/50 rounded-xl border">
                      <div className="text-sm font-medium mb-2">Service Summary</div>
                      <div className="grid grid-cols-2 md:grid-cols-5 gap-2 text-sm">
                        <div>
                          <div className="text-muted-foreground">Total Days</div>
                          <div className="font-semibold">{dayCountsPreview.total_days}</div>
                        </div>
                        <div>
                          <div className="text-muted-foreground">At Sea</div>
                          <div className="font-semibold">{dayCountsPreview.at_sea_days}</div>
                        </div>
                        <div>
                          <div className="text-muted-foreground">Standby</div>
                          <div className="font-semibold">{dayCountsPreview.standby_days}</div>
                        </div>
                        <div>
                          <div className="text-muted-foreground">Yard</div>
                          <div className="font-semibold">{dayCountsPreview.yard_days}</div>
                </div>
                                        <div>
                          <div className="text-muted-foreground">Leave</div>
                          <div className="font-semibold">{dayCountsPreview.leave_days}</div>
                        </div>
                                        </div>
                                    </div>
                  )}

                  {/* Only show captain email field if no active captain found (captain info already shown in Current Vessel card above) */}
                  {!activeCaptain && !isCheckingCaptain && (
                    <FormField
                      control={form.control}
                      name="captain_email"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel>Captain Email (Optional)</FormLabel>
                          <FormControl>
                            <Input
                              type="email"
                              placeholder="captain@vessel.com"
                              className="rounded-xl"
                              {...field}
                            />
                          </FormControl>
                          <FormDescription>
                            If provided, the captain will receive an email to sign off on this testimonial. If this vessel has an active captain on SeaJourney, they will be selected automatically.
                          </FormDescription>
                          <FormMessage />
                        </FormItem>
                      )}
                    />
                  )}


                  <DialogFooter>
                    <Button
                      type="button"
                      variant="outline"
                      onClick={() => {
                        form.reset();
                        setActiveCaptain(null);
                        setIsDialogOpen(false);
                      }}
                      className="rounded-xl"
                    >
                      Cancel
                    </Button>
                    <Button
                      type="submit"
                      disabled={isSaving}
                      className="rounded-xl"
                    >
                      {isSaving ? (
                        <>
                          <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                          Saving...
                        </>
                      ) : (
                        <>
                          {activeCaptain ? (
                            <>
                              <Mail className="mr-2 h-4 w-4" />
                              Send to Captain's Inbox
                            </>
                          ) : form.watch('captain_email') ? (
                            <>
                              <Mail className="mr-2 h-4 w-4" />
                              Send Request
                            </>
                          ) : (
                            'Save as Draft'
                          )}
                        </>
                      )}
                    </Button>
                  </DialogFooter>
                </form>
              </Form>
            </DialogContent>
          </Dialog>
        </div>
        <Separator />
      </div>

      {/* Testimonials Table */}
      {isLoading ? (
        <div className="flex items-center justify-center py-12">
          <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
                                </div>
      ) : (
        <Card className="rounded-xl border">
          <CardHeader>
            <CardTitle>Testimonial Requests</CardTitle>
                            </CardHeader>
                            <CardContent>
            <Tabs value={activeTab} onValueChange={(value) => setActiveTab(value as any)} className="w-full">
              <TabsList className="grid w-full grid-cols-5 mb-6 rounded-xl">
                <TabsTrigger value="all">All</TabsTrigger>
                <TabsTrigger value="draft">Draft</TabsTrigger>
                <TabsTrigger value="pending">Pending</TabsTrigger>
                <TabsTrigger value="approved">Approved</TabsTrigger>
                <TabsTrigger value="rejected">Rejected</TabsTrigger>
              </TabsList>
              <TabsContent value={activeTab} className="mt-0">
                {filteredTestimonials.length === 0 ? (
                  <div className="flex flex-col items-center justify-center py-12 ">
                    <LifeBuoy className="h-12 w-12 text-muted-foreground mb-4 " />
                    <h3 className="text-lg font-semibold mb-2">No Testimonials</h3>
                    <p className="text-sm text-muted-foreground text-center max-w-md">
                      {activeTab === 'all' 
                        ? "You haven't created any testimonials yet. Click \"Request Testimonial\" to get started."
                        : `You don't have any ${activeTab} testimonials.`}
                    </p>
                  </div>
                ) : (
                  <Table>
                    <TableHeader>
                      <TableRow>
                        <TableHead>Vessel</TableHead>
                        <TableHead>Date Range</TableHead>
                        <TableHead>Days</TableHead>
                        <TableHead>Captain</TableHead>
                        <TableHead>Status</TableHead>
                        <TableHead>Created</TableHead>
                        <TableHead>PDF</TableHead>
                        <TableHead className="w-[100px]">Actions</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {filteredTestimonials.map((testimonial) => {
                        const isExpanded = expandedTestimonials.has(testimonial.id);
                        const hasRejectionMessage = testimonial.status === 'rejected' && testimonial.notes;
                        
                        // Extract rejection reason from notes
                        let rejectionReason = '';
                        if (testimonial.notes) {
                          if (testimonial.notes.includes('Rejection reason:')) {
                            rejectionReason = testimonial.notes.split('Rejection reason:')[1]?.trim() || '';
                          } else {
                            // If no prefix, use the whole notes field
                            rejectionReason = testimonial.notes;
                          }
                        }
                        
                        return (
                          <React.Fragment key={testimonial.id}>
                            <TableRow>
                              <TableCell className="font-medium">
                                <div className="flex items-center gap-2">
                                  <Ship className="h-4 w-4 text-muted-foreground" />
                                  {getVesselName(testimonial.vessel_id)}
                                </div>
                              </TableCell>
                              <TableCell>
                                <div className="flex items-center gap-2 text-sm">
                                  <Calendar className="h-4 w-4 text-muted-foreground" />
                                  {format(new Date(testimonial.start_date), 'MMM d, yyyy')} - {format(new Date(testimonial.end_date), 'MMM d, yyyy')}
                                </div>
                              </TableCell>
                              <TableCell>
                                <div className="text-sm">
                                  <div className="font-medium">{testimonial.total_days} total</div>
                                  <div className="text-muted-foreground text-xs">
                                    {testimonial.at_sea_days} at sea, {testimonial.standby_days} standby
                                  </div>
                                </div>
                              </TableCell>
                              <TableCell>
                                {testimonial.captain_email ? (
                                  <div className="flex items-center gap-2">
                                    <Mail className="h-4 w-4 text-muted-foreground" />
                                    <div>
                                      {testimonial.captain_name && (
                                        <div className="font-medium text-sm">{testimonial.captain_name}</div>
                                      )}
                                      <div className="text-sm text-muted-foreground">{testimonial.captain_email}</div>
                                    </div>
                                  </div>
                                ) : (
                                  <span className="text-sm text-muted-foreground">—</span>
                                )}
                              </TableCell>
                              <TableCell>
                                <div className="flex items-center gap-2">
                                  {getStatusBadge(testimonial.status)}
                                  {hasRejectionMessage && (
                                    <Button
                                      variant="ghost"
                                      size="sm"
                                      onClick={() => {
                                        const newExpanded = new Set(expandedTestimonials);
                                        if (newExpanded.has(testimonial.id)) {
                                          newExpanded.delete(testimonial.id);
                                        } else {
                                          newExpanded.add(testimonial.id);
                                        }
                                        setExpandedTestimonials(newExpanded);
                                      }}
                                      className="h-6 w-6 p-0"
                                    >
                                      {isExpanded ? (
                                        <ChevronUp className="h-4 w-4" />
                                      ) : (
                                        <ChevronDown className="h-4 w-4" />
                                      )}
                                    </Button>
                                  )}
                                </div>
                              </TableCell>
                              <TableCell className="text-sm text-muted-foreground">
                                {format(new Date(testimonial.created_at), 'MMM d, yyyy')}
                              </TableCell>
                              <TableCell>
                                {testimonial.pdf_url ? (
                                  <a 
                                    href={testimonial.pdf_url} 
                                    target="_blank" 
                                    rel="noopener noreferrer"
                                    className="text-primary hover:underline text-sm"
                                  >
                                    View PDF
                                  </a>
                                ) : testimonial.status === 'approved' ? (
                                  <Button
                                    variant="outline"
                                    size="sm"
                                    onClick={() => handleGeneratePDF(testimonial)}
                                    className="rounded-xl"
                                  >
                                    <Download className="mr-2 h-4 w-4" />
                                    Generate PDF
                                  </Button>
                                ) : (
                                  <span className="text-sm text-muted-foreground">—</span>
                                )}
                              </TableCell>
                              <TableCell>
                                {testimonial.status !== 'approved' ? (
                                  <Button
                                    variant="ghost"
                                    size="sm"
                                    onClick={() => setTestimonialToDelete(testimonial)}
                                    className="rounded-xl text-destructive hover:text-destructive hover:bg-destructive/10"
                                  >
                                    <Trash2 className="h-4 w-4" />
                                  </Button>
                                ) : (
                                  <span className="text-sm text-muted-foreground">—</span>
                                )}
                              </TableCell>
                            </TableRow>
                            {isExpanded && hasRejectionMessage && (
                              <TableRow>
                                <TableCell colSpan={8} className="bg-red-50 dark:bg-red-950/20 p-0">
                                  <div className="p-4 space-y-3">
                                    <div className="flex items-start gap-3">
                                      <AlertCircle className="h-5 w-5 text-red-600 dark:text-red-400 mt-0.5 flex-shrink-0" />
                                      <div className="flex-1 space-y-3">
                                        <div>
                                          <div className="font-semibold text-sm text-red-900 dark:text-red-100 mb-2">
                                            Rejection Details
                                          </div>
                                          <div className="text-sm text-red-800 dark:text-red-200 whitespace-pre-wrap bg-white dark:bg-gray-900 p-4 rounded-lg border border-red-200 dark:border-red-800 max-h-96 overflow-y-auto">
                                            {rejectionReason.split('--- State Mismatches Found ---').map((section, idx) => {
                                              if (idx === 0) {
                                                // Main rejection reason
                                                return section.trim() ? (
                                                  <div key={idx} className="mb-4">
                                                    <div className="font-medium mb-2">Reason:</div>
                                                    <div className="text-red-900 dark:text-red-100">{section.trim()}</div>
                                                  </div>
                                                ) : null;
                                              } else {
                                                // Mismatch details section
                                                const mismatchParts = section.split('\n').filter(line => line.trim());
                                                return (
                                                  <div key={idx} className="mt-4 pt-4 border-t border-red-200 dark:border-red-800">
                                                    <div className="font-medium mb-3 text-red-900 dark:text-red-100">
                                                      State Mismatches Found
                                                    </div>
                                                    <div className="space-y-2 text-sm">
                                                      {mismatchParts.map((line, lineIdx) => {
                                                        if (line.includes('Total mismatches:')) {
                                                          return (
                                                            <div key={lineIdx} className="font-semibold text-red-900 dark:text-red-100 mb-2">
                                                              {line}
                                                            </div>
                                                          );
                                                        } else if (line.match(/^\d+\./)) {
                                                          // Mismatch line
                                                          return (
                                                            <div key={lineIdx} className="text-red-800 dark:text-red-200 pl-4">
                                                              {line}
                                                            </div>
                                                          );
                                                        } else if (line.includes('more mismatch')) {
                                                          return (
                                                            <div key={lineIdx} className="text-red-700 dark:text-red-300 italic pl-4">
                                                              {line}
                                                            </div>
                                                          );
                                                        } else if (line.trim() && !line.includes('Please review')) {
                                                          return (
                                                            <div key={lineIdx} className="text-red-800 dark:text-red-200">
                                                              {line}
                                                            </div>
                                                          );
                                                        } else if (line.includes('Please review')) {
                                                          return (
                                                            <div key={lineIdx} className="mt-3 pt-3 border-t border-red-200 dark:border-red-800 text-red-900 dark:text-red-100 font-medium">
                                                              {line}
                                                            </div>
                                                          );
                                                        }
                                                        return null;
                                                      })}
                                                    </div>
                                                  </div>
                                                );
                                              }
                                            })}
                                          </div>
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                </TableCell>
                              </TableRow>
                            )}
                          </React.Fragment>
                        );
                      })}
                    </TableBody>
                  </Table>
                )}
              </TabsContent>
            </Tabs>
                            </CardContent>
                        </Card>
            )}

      {/* Delete Confirmation Dialog */}
      <AlertDialog open={!!testimonialToDelete} onOpenChange={(open) => !open && setTestimonialToDelete(null)}>
        <AlertDialogContent className="rounded-xl">
          <AlertDialogHeader>
            <AlertDialogTitle>Delete Testimonial?</AlertDialogTitle>
            <AlertDialogDescription>
              Are you sure you want to delete this testimonial? This action cannot be undone.
              {testimonialToDelete && (
                <>
                  <br />
                  <br />
                  <span className="font-medium">
                    {getVesselName(testimonialToDelete.vessel_id)} - {format(new Date(testimonialToDelete.start_date), 'MMM d, yyyy')} to {format(new Date(testimonialToDelete.end_date), 'MMM d, yyyy')}
                  </span>
                </>
              )}
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel disabled={isDeleting} className="rounded-xl">Cancel</AlertDialogCancel>
            <AlertDialogAction
              onClick={() => testimonialToDelete && handleDeleteTestimonial(testimonialToDelete)}
              disabled={isDeleting}
              className="rounded-xl bg-destructive text-destructive-foreground hover:bg-destructive/90"
            >
              {isDeleting ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Deleting...
                </>
              ) : (
                <>
                  <Trash2 className="mr-2 h-4 w-4" />
                  Delete Permanently
                </>
              )}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
        </div>
    );
}
