-- Add vessel context to nav_watch_applications so vessel-generated documents can be stored and listed per crew member
-- When a vessel manager generates a Nav Watch document for a crew member, we set vessel_id and vessel_user_id

ALTER TABLE public.nav_watch_applications
ADD COLUMN IF NOT EXISTS vessel_id UUID REFERENCES public.vessels(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS vessel_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_nav_watch_applications_vessel_id ON public.nav_watch_applications(vessel_id);
CREATE INDEX IF NOT EXISTS idx_nav_watch_applications_vessel_user_id ON public.nav_watch_applications(vessel_user_id);

COMMENT ON COLUMN public.nav_watch_applications.vessel_id IS 'Set when generated by a vessel manager for a crew member; NULL when generated by the user themselves';
COMMENT ON COLUMN public.nav_watch_applications.vessel_user_id IS 'Vessel manager who generated this (when vessel_id is set)';

-- RLS: Vessel managers can view nav watch applications for crew assigned to their active vessel
DROP POLICY IF EXISTS "Users can view their own nav watch applications" ON public.nav_watch_applications;
CREATE POLICY "Users can view their own nav watch applications"
ON public.nav_watch_applications
FOR SELECT
USING (
  auth.uid() = user_id
  OR
  EXISTS (
    SELECT 1 FROM public.vessel_assignments va
    JOIN public.users u ON u.id = auth.uid()
    WHERE va.user_id = nav_watch_applications.user_id
    AND (u.role = 'vessel' AND va.vessel_id = u.active_vessel_id OR u.role = 'admin')
  )
);

-- RLS: Vessel managers can create nav watch applications for crew on their vessel (with vessel_id set)
DROP POLICY IF EXISTS "Users can create their own nav watch applications" ON public.nav_watch_applications;
CREATE POLICY "Users can create their own nav watch applications"
ON public.nav_watch_applications
FOR INSERT
WITH CHECK (
  auth.uid() = user_id
  OR
  (vessel_id IS NOT NULL AND vessel_user_id = auth.uid() AND EXISTS (
    SELECT 1 FROM public.vessel_assignments va
    JOIN public.users u ON u.id = auth.uid()
    WHERE va.user_id = nav_watch_applications.user_id
    AND va.vessel_id = nav_watch_applications.vessel_id
    AND (u.role = 'vessel' AND u.active_vessel_id = va.vessel_id OR u.role = 'admin')
  ))
);

-- RLS: Vessel managers can delete applications they generated (vessel_user_id = auth.uid())
DROP POLICY IF EXISTS "Users can delete their own nav watch applications" ON public.nav_watch_applications;
CREATE POLICY "Users can delete their own nav watch applications"
ON public.nav_watch_applications
FOR DELETE
USING (
  auth.uid() = user_id
  OR
  (vessel_user_id = auth.uid())
);
