-- Add verification code to proof_of_service. Generated by the database on row insert.
-- Format POS-XXXXXXXX (8 chars after prefix) for use with the same verify system as testimonials.

ALTER TABLE public.proof_of_service
ADD COLUMN IF NOT EXISTS verification_code TEXT NOT NULL
DEFAULT ('POS-' || upper(substring(replace(gen_random_uuid()::text, '-', ''), 1, 8)));

-- Backfill existing rows to POS-XXXXXXXX (take first 8 chars of existing code if no POS- prefix)
UPDATE public.proof_of_service
SET verification_code = 'POS-' || upper(substring(replace(verification_code, 'POS-', ''), 1, 8))
WHERE verification_code IS NOT NULL AND verification_code NOT LIKE 'POS-%';

COMMENT ON COLUMN public.proof_of_service.verification_code IS
'Unique code in format POS-XXXXXXXX, generated on insert for verification (same system as testimonials).';
