-- Create nav_watch_applications table to store MCA Watch Rating Certificate applications
-- This allows users to save and re-download their applications

CREATE TABLE IF NOT EXISTS public.nav_watch_applications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  
  -- User reference
  user_id UUID NOT NULL,
  
  -- Certificate type
  certificate_type TEXT NOT NULL CHECK (certificate_type IN ('navigational', 'engine_room', 'electro_technical')),
  
  -- Personal details (stored as JSONB for flexibility)
  personal_details JSONB NOT NULL,
  
  -- Sea service records (stored as JSONB array)
  sea_service_records JSONB NOT NULL DEFAULT '[]'::jsonb,
  
  -- Metadata
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add foreign key constraint if it doesn't exist
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint 
    WHERE conname = 'nav_watch_applications_user_id_fkey'
  ) THEN
    ALTER TABLE public.nav_watch_applications
    ADD CONSTRAINT nav_watch_applications_user_id_fkey 
    FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
  END IF;
END $$;

-- Create indexes for efficient querying (only if they don't exist)
CREATE INDEX IF NOT EXISTS idx_nav_watch_applications_user_id ON public.nav_watch_applications(user_id);
CREATE INDEX IF NOT EXISTS idx_nav_watch_applications_created_at ON public.nav_watch_applications(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_nav_watch_applications_certificate_type ON public.nav_watch_applications(certificate_type);

-- Enable RLS
ALTER TABLE public.nav_watch_applications ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Users can view their own applications
DROP POLICY IF EXISTS "Users can view their own nav watch applications" ON public.nav_watch_applications;
CREATE POLICY "Users can view their own nav watch applications"
ON public.nav_watch_applications
FOR SELECT
USING (auth.uid() = user_id);

-- RLS Policy: Users can create their own applications
DROP POLICY IF EXISTS "Users can create their own nav watch applications" ON public.nav_watch_applications;
CREATE POLICY "Users can create their own nav watch applications"
ON public.nav_watch_applications
FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- RLS Policy: Users can update their own applications
DROP POLICY IF EXISTS "Users can update their own nav watch applications" ON public.nav_watch_applications;
CREATE POLICY "Users can update their own nav watch applications"
ON public.nav_watch_applications
FOR UPDATE
USING (auth.uid() = user_id);

-- RLS Policy: Users can delete their own applications
DROP POLICY IF EXISTS "Users can delete their own nav watch applications" ON public.nav_watch_applications;
CREATE POLICY "Users can delete their own nav watch applications"
ON public.nav_watch_applications
FOR DELETE
USING (auth.uid() = user_id);

-- RLS Policy: Admins can view all applications
DROP POLICY IF EXISTS "Admins can view all nav watch applications" ON public.nav_watch_applications;
CREATE POLICY "Admins can view all nav watch applications"
ON public.nav_watch_applications
FOR SELECT
USING (
  EXISTS (
    SELECT 1 FROM public.users
    WHERE id = auth.uid() AND role = 'admin'
  )
);

-- Add comments
COMMENT ON TABLE public.nav_watch_applications IS 'Stores MCA Watch Rating Certificate applications generated by users';
COMMENT ON COLUMN public.nav_watch_applications.certificate_type IS 'Type of certificate: navigational, engine_room, or electro_technical';
COMMENT ON COLUMN public.nav_watch_applications.personal_details IS 'JSONB object containing personal details (surname, forenames, dateOfBirth, address, etc.)';
COMMENT ON COLUMN public.nav_watch_applications.sea_service_records IS 'JSONB array of sea service records (vessel details, dates, days at sea, etc.)';
