-- Create vessel_generated_testimonials table for testimonials generated by vessel managers
-- These are separate from the main testimonials table since they don't go through the verification system

CREATE TABLE IF NOT EXISTS public.vessel_generated_testimonials (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  
  -- Crew member information
  crew_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  
  -- Vessel information
  vessel_id UUID NOT NULL REFERENCES public.vessels(id) ON DELETE CASCADE,
  vessel_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, -- Vessel manager who generated this
  
  -- Service dates
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  
  -- Service breakdown
  total_days INTEGER NOT NULL,
  at_sea_days INTEGER NOT NULL,
  standby_days INTEGER NOT NULL,
  yard_days INTEGER NOT NULL,
  leave_days INTEGER NOT NULL,
  
  -- Vessel manager information (who generated this)
  generated_by_name TEXT NOT NULL, -- Name of vessel manager who generated this
  generated_by_email TEXT NULL, -- Email of vessel manager
  
  -- Data source
  data_source TEXT NOT NULL CHECK (data_source IN ('crew', 'vessel')), -- 'crew' for crew member logs, 'vessel' for vessel logs
  
  -- Notes
  notes TEXT NULL,
  
  -- PDF format used
  pdf_format TEXT NOT NULL DEFAULT 'seajourney' CHECK (pdf_format IN ('seajourney', 'mca', 'amsa')),

  -- AMSA 771 reference section (JSON); only used when pdf_format = 'amsa'
  amsa_reference_data JSONB DEFAULT NULL,
  
  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  
  -- Ensure end_date is after start_date
  CONSTRAINT end_after_start CHECK (end_date >= start_date)
);

-- Create indexes for common queries
CREATE INDEX IF NOT EXISTS idx_vessel_generated_testimonials_crew_user_id 
ON public.vessel_generated_testimonials(crew_user_id);

CREATE INDEX IF NOT EXISTS idx_vessel_generated_testimonials_vessel_id 
ON public.vessel_generated_testimonials(vessel_id);

CREATE INDEX IF NOT EXISTS idx_vessel_generated_testimonials_vessel_user_id 
ON public.vessel_generated_testimonials(vessel_user_id);

CREATE INDEX IF NOT EXISTS idx_vessel_generated_testimonials_created_at 
ON public.vessel_generated_testimonials(created_at DESC);

-- Enable RLS
ALTER TABLE public.vessel_generated_testimonials ENABLE ROW LEVEL SECURITY;

-- RLS Policies — drop first so re-running this script does not fail with "policy already exists"
DROP POLICY IF EXISTS "Vessel managers can view testimonials they generated" ON public.vessel_generated_testimonials;
DROP POLICY IF EXISTS "Vessel managers can insert testimonials for crew with approved access" ON public.vessel_generated_testimonials;
DROP POLICY IF EXISTS "Vessel managers can update testimonials they generated" ON public.vessel_generated_testimonials;
DROP POLICY IF EXISTS "Vessel managers can delete testimonials they generated" ON public.vessel_generated_testimonials;

-- Vessel managers can view testimonials they generated for their crew
CREATE POLICY "Vessel managers can view testimonials they generated"
ON public.vessel_generated_testimonials
FOR SELECT
USING (
  -- Vessel manager can view testimonials they generated
  vessel_user_id = auth.uid()
  OR
  -- Crew member can view their own testimonials
  crew_user_id = auth.uid()
  OR
  -- Admins can view all
  EXISTS (
    SELECT 1 FROM public.users
    WHERE id = auth.uid() AND role = 'admin'
  )
);

-- Vessel managers with approved access can insert testimonials for crew members
CREATE POLICY "Vessel managers can insert testimonials for crew with approved access"
ON public.vessel_generated_testimonials
FOR INSERT
WITH CHECK (
  -- Allow if user is a vessel manager with an approved access request for this crew member
  EXISTS (
    SELECT 1
    FROM public.vessel_sea_time_access_requests vsar
    JOIN public.users u ON u.id = auth.uid()
    WHERE vsar.vessel_user_id = auth.uid()
      AND vsar.crew_user_id = vessel_generated_testimonials.crew_user_id
      AND vsar.vessel_id = vessel_generated_testimonials.vessel_id
      AND vsar.status = 'approved'
      AND u.role = 'vessel'
  )
  OR
  -- Admins can create any testimonial
  EXISTS (
    SELECT 1 FROM public.users
    WHERE id = auth.uid() AND role = 'admin'
  )
);

-- Vessel managers can update testimonials they generated (for corrections)
CREATE POLICY "Vessel managers can update testimonials they generated"
ON public.vessel_generated_testimonials
FOR UPDATE
USING (
  vessel_user_id = auth.uid()
  OR
  EXISTS (
    SELECT 1 FROM public.users
    WHERE id = auth.uid() AND role = 'admin'
  )
)
WITH CHECK (
  vessel_user_id = auth.uid()
  OR
  EXISTS (
    SELECT 1 FROM public.users
    WHERE id = auth.uid() AND role = 'admin'
  )
);

-- Vessel managers can delete testimonials they generated
CREATE POLICY "Vessel managers can delete testimonials they generated"
ON public.vessel_generated_testimonials
FOR DELETE
USING (
  vessel_user_id = auth.uid()
  OR
  EXISTS (
    SELECT 1 FROM public.users
    WHERE id = auth.uid() AND role = 'admin'
  )
);

-- Add comments
COMMENT ON TABLE public.vessel_generated_testimonials IS 
'Testimonials generated by vessel managers for crew members. These are separate from the main testimonials table since they do not go through the captain approval/verification system.';

COMMENT ON COLUMN public.vessel_generated_testimonials.crew_user_id IS 
'Reference to the crew member this testimonial is for';

COMMENT ON COLUMN public.vessel_generated_testimonials.vessel_user_id IS 
'Reference to the vessel manager who generated this testimonial';

COMMENT ON COLUMN public.vessel_generated_testimonials.data_source IS 
'Data source used: "crew" for crew member logs, "vessel" for vessel logs';

COMMENT ON COLUMN public.vessel_generated_testimonials.pdf_format IS 
'PDF format used: "seajourney" or "mca"';
