-- Proof of Service: vessel-generated records of a crew member's time on board.
-- Crew can accumulate multiple entries (one per vessel/period) and use them as proof of experience.
-- Vessel generates from Crew page and can "Save to crew profile" so the crew member keeps it.

CREATE TABLE IF NOT EXISTS public.proof_of_service (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Crew member this proof is for
  crew_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  -- Vessel and who generated
  vessel_id UUID NOT NULL REFERENCES public.vessels(id) ON DELETE CASCADE,
  vessel_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  -- Service period
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,

  -- Sea time breakdown (MCA-style)
  total_days INTEGER NOT NULL,
  at_sea_days INTEGER NOT NULL,
  standby_days INTEGER NOT NULL,
  yard_days INTEGER NOT NULL,
  leave_days INTEGER NOT NULL,

  -- Snapshot at generation (so document is self-contained)
  vessel_name TEXT NOT NULL,
  vessel_type TEXT NULL,
  vessel_imo TEXT NULL,
  crew_name TEXT NOT NULL,
  crew_position TEXT NULL,

  -- Who generated
  generated_by_name TEXT NOT NULL,
  generated_by_email TEXT NULL,
  data_source TEXT NOT NULL CHECK (data_source IN ('crew', 'vessel')),
  notes TEXT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT proof_end_after_start CHECK (end_date >= start_date)
);

CREATE INDEX IF NOT EXISTS idx_proof_of_service_crew_user_id ON public.proof_of_service(crew_user_id);
CREATE INDEX IF NOT EXISTS idx_proof_of_service_vessel_id ON public.proof_of_service(vessel_id);
CREATE INDEX IF NOT EXISTS idx_proof_of_service_vessel_user_id ON public.proof_of_service(vessel_user_id);
CREATE INDEX IF NOT EXISTS idx_proof_of_service_created_at ON public.proof_of_service(created_at DESC);

ALTER TABLE public.proof_of_service ENABLE ROW LEVEL SECURITY;

-- Crew can view their own proof of service entries
CREATE POLICY "Crew can view own proof of service"
ON public.proof_of_service
FOR SELECT
USING (crew_user_id = auth.uid());

-- Vessel managers can view proof they generated
CREATE POLICY "Vessel managers can view proof they generated"
ON public.proof_of_service
FOR SELECT
USING (
  vessel_user_id = auth.uid()
  OR EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin')
);

-- Vessel managers can insert for crew on their active vessel (same pattern as vessel_generated_testimonials)
CREATE POLICY "Vessel managers can insert proof for crew on their vessel"
ON public.proof_of_service
FOR INSERT
WITH CHECK (
  vessel_user_id = auth.uid()
  AND EXISTS (
    SELECT 1 FROM public.users u
    WHERE u.id = auth.uid()
      AND u.role = 'vessel'
      AND u.active_vessel_id = proof_of_service.vessel_id
  )
);

-- Admins can insert
CREATE POLICY "Admins can insert proof of service"
ON public.proof_of_service
FOR INSERT
WITH CHECK (EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin'));

-- Vessel managers can delete proof they generated (e.g. correction)
CREATE POLICY "Vessel managers can delete proof they generated"
ON public.proof_of_service
FOR DELETE
USING (
  vessel_user_id = auth.uid()
  OR EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin')
);

-- updated_at trigger
DROP TRIGGER IF EXISTS trg_proof_of_service_updated_at ON public.proof_of_service;
CREATE TRIGGER trg_proof_of_service_updated_at
BEFORE UPDATE ON public.proof_of_service
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

COMMENT ON TABLE public.proof_of_service IS
'Proof of service records generated by vessels for crew members. Each row is one period on one vessel. Crew accumulate these over time as proof of experience.';
COMMENT ON COLUMN public.proof_of_service.data_source IS
'Source of sea time data: crew = crew member logs, vessel = vessel logs (when crew has not granted access).';
